### PR TITLE
Make /allocation query path and port configurable, which should enable support for pure-OSS OpenCost

### PR DESCRIPTION
**Pull request by michaelmdresser**
## What does this PR change?

This change should allow kubectl-cost to interact successfully with
pure-OSS OpenCost (for most commands). This is achieved by making
the Allocation query path (e.g. `/model/allocation`) and the service query port
(e.g. `9090`) configurable and by making the currency code query (`/getConfigs`)
fail gracefully into an empty string (with a warning log). Users of OpenCost
should be able to set the Allocation query path to `/allocation/compute` (or similar)
and the service port to `9003` (or similar).

This change includes a more generic command builder for standard
aggregation commands to reduce code duplication substantially. Its still
a tad rough around the edges, but I think its an overall improvement
which should make future changes easier. The output tables are now built
more programmatically by understanding the aggregation. Ideally we would
eliminate the cluster column if there is only one cluster present, but
that's a future task.

## How does this PR impact users? (This is the kind of thing that goes in release notes!)

- Adds support for using kubectl-cost with OpenCost. See `--help` for suggested settings for `--service-port` and `--allocation-path` for OpenCost support.

## PR dependencies

- https://github.com/kubecost/kubectl-cost/pull/114 (to reduce the review surface here)

## How was this PR tested?

Local testing of all commands. Integration test script ran successfully locally (against a standard Kubecost install). I haven't yet tested with OpenCost.

## Have you made an update to documentation?

Yes, see README updates.

### CODE REVIEW

**Comment by michaelmdresser** [comment]
TODO: Add a note that this drops support for Kubecost versions before the introduction of `/model/allocation/summary`.

**Comment by michaelmdresser** [comment]
@jessegoodier once this PR gets merged and a new release of `kubectl cost` is cut, we should be able to test OpenCost functionality.

**Comment by dramich** [comment]
> TODO: Add a note that this drops support for Kubecost versions before the introduction of `/model/allocation/summary`.

When was this added? Our predisposition to break our users is concerning to me especially when this looks like a place where a split in the code path would be possible.

**Comment by nikovacevic** [comment]
Woah! When (and why) did we add that endpoint to OpenCost? That's not even a documented endpoint in the closed source!

**Comment by nikovacevic** [comment]
@AjayTripathy why did we do this? https://github.com/kubecost/opencost/commit/2c47dbcea29c99b61271356d8d5b9ce2046ddce4

The SummaryAllocation types are already in the open source (see https://github.com/kubecost/opencost/blob/develop/pkg/kubecost/summaryallocation.go)

And I thought we had agreed to keep Allocation Summary API internal -- or at least, we intentionally haven't documented it. I'm thinking we should document if that's going to be used in OpenCost.

**Comment by nikovacevic** [comment]
Also, @michaelmdresser there is an Allocation API present in OpenCost right now. It's just filed under `/allocation/compute`: https://github.com/kubecost/opencost/blob/develop/pkg/costmodel/router.go#L1629

Now that `router.go` has been separated from `cmd/costmodel/costmodel.go`, we could register that handler under just `/allocation` if the idea is just to be compatible.

(I'm also not necessarily opposed to using Allocation Summary API -- but to echo Dan's sentiment, let's make sure we don't break anyone, and let's document the features that we open source!)

**Comment by AjayTripathy** [comment]
Hey @nikovacevic I did this as a quick way to support interoperability between open and closed source for the frontend.

**Comment by AjayTripathy** [comment]
I think it should be easy to preserve backwards compatibility here? Just check what version of kubecost is running and use that one? Or fallback if something 404s?

**Comment by michaelmdresser** [comment]
Thanks for the commentary everyone.

@dramich I completely agree that this isn't good, thanks for catching me on this. I've reverted the new `/allocation/summary` query and continued to use the previous behavior that queries `/model/allocation` which will maintain compatibility. OpenCost support will instead be achievable with the new `--service-port` and `--allocation-path` flags with the settings suggested in the `--help`. This dovetails nicely with @nikovacevic's concerns about using undocumented endpoints in open source code.

@nikovacevic thanks for pointing out that `/allocation/compute` is available in OpenCost -- I clearly didn't dig deep enough and just saw [this](https://github.com/kubecost/opencost/blob/040df8955b01af129898b9c980415c9553cd1ec2/pkg/cmd/costmodel/costmodel.go#L30). For the time being, I think it's okay to ask users to use the new flags to manually update the query path. A more robust solution could be to either (1) try to intelligently select an endpoint/port combo to serve our queries from a predetermined list or (2) do something like https://github.com/kubecost/kubectl-cost/issues/107 to add env vars like `KUBECTL_COST_SERVICE_PORT` and `KUBECTL_COST_ALLOCATION_PATH` to enable more persistent configuration.

If we do want to add support for summary at some point in the future, a code path fork seems like the right call.

**Comment by michaelmdresser** [comment]
This PR has been split into multiple parts.

- Fixing a problem if failed/stopped/completed cost-analyzer Pods exist in the cluster: https://github.com/kubecost/kubectl-cost/pull/115
- The big refactor which reduces code duplication: https://github.com/kubecost/kubectl-cost/pull/116
- Adding OpenCost support (requires refactor PR): https://github.com/kubecost/kubectl-cost/pull/117
- Make log level configurable: https://github.com/kubecost/kubectl-cost/pull/118

**Pull request closed without merging**
