### PR TITLE
Fix "label" actually displaying namespace results

### PR DESCRIPTION
**Pull request by michaelmdresser**

### CODE REVIEW

**Comment by pierluigilenoci** [comment]
Hi @michaelmdresser, I'm not able to update to version 0.2.2 with brew.
Could you please take a look?

**Comment by dwbrown2** [comment]
@pierluigilenoci did you mean `krew` in your last message?

**Comment by pierluigilenoci** [comment]
Yes, of course. My bad.

**Comment by michaelmdresser** [comment]
Hi @pierluigilenoci, I'm able to successfully install the latest version (`v0.2.2`) of `kubectl cost` with
```
kubectl krew install cost
```
if not already installed

and
```
kubectl krew upgrade cost
```
if already installed.

Are you running `kubectl krew update`? That only updates the plugin index, not any of the plugins themselves.

**Comment by pierluigilenoci** [comment]
@michaelmdresser worked, thanks! ❤️

**Pull request merged**
